### ISSUE TITLE
client will stuck after trying to acquire the lock 5 times

### ISSUE THREAD

**Issue by hkjeffchan** [ORESoftware/live-mutex#17] opened 2018-05-28 18:05 UTC
What I am trying to do is to write a higher level function to lock an array of keys and if one of them fails, unlock all acquired locks and sleep 1 second and retry. I created a client with lockRetryMax=2 and reuse the client in the same function. But when it tries to acquire the same lock 5 times, it just hang.

I found that in [src/client.ts](https://github.com/ORESoftware/live-mutex/blob/master/src/client.ts), it is hardcoded to 5 in the following line, any reason for that? It doesn't resolve/reject the promise after 5 attempts right now. It seems deadlock right now.

`````
    if (rawLockCount - unlockCount > 5) {
      this.lockQueues[key].unshift(arguments);
    }
    else {
      this.lockInternal.apply(this, arguments);
    }
`````

**Comment by ORESoftware** [comment] 2018-05-28 18:09
Ah interesting, that was experimental code that wasn't supposed to make it into production.
Let me fix it.

In the meantime, change it to this one line, and see if the problem goes away:

` this.lockInternal.apply(this, arguments);`

**Comment by hkjeffchan** [comment] 2018-05-28 18:16
yes, it works.

**Comment by ORESoftware** [comment] 2018-05-28 18:19
ok good, try installing this new version:

`live-mutex@0.0.10040`

I just published it. I made some changes to the codebase in the last 10 days, so it's not exactly the most stable thing, let me know if you see anything strange.

**Comment by hkjeffchan** [comment] 2018-05-28 18:32
work well!

I got more error/questions.
1) The client option in the typescript definition got ttl option but if i pass ttl, it will fail with
Error: An option passed to Live-Mutex Client constructor is not a recognized option => "ttl"
ttl can be passed with lockp without a problem

2) The ttl should be infinity by default in my opinion. Took me a while to recognize that it will unlock itself!!!

3) I can only bind the process with 'warning' event but not 'error'.
````
process.on('warning', err => {
    console.log(err);
});
````

I got the following typescript compile error if change 'warning' to 'error'
Argument of type '"error"' is not assignable to parameter of type 'Signals'

**Comment by ORESoftware** [comment] 2018-05-28 19:19
@hkjeffchan yes live-mutex is really performant for certain niche use cases, not just in speed, but CPU usage.

the compilation error is probably for Node.js core types, live-mutex is currently compiling without errors.

to skip typescript compilation for libraries (everything in node_modules) use this option `skipLibCheck:true` in your tsconfig.json. 

Yeah let me think about the `ttl` default. Basically this library has a sweet spot where critical sections take less than about 5 seconds.

For now, maybe set your `ttl` to 20000 (20 seconds) or whatever you need.

let me get back to you on the other things in an hour or so.

**Comment by ORESoftware** [comment] 2018-05-28 19:21
I think I will change the `ttl` default to something like 100 seconds, and make a note of that in the README.

**Comment by ORESoftware** [comment] 2018-05-28 19:30
@hkjeffchan  I fixed it - `ttl` option to the Client constructor is now fine, that was an options validation bug.

Also, you should only use `process.on('warning')`, I removed the warning in the codebase - you do not need to listen for `process.on('error')` anymore.

install a new version:

```
live-mutex@0.0.10041
```

that new version has your fixes.

**Comment by hkjeffchan** [comment] 2018-05-28 21:12
It seems it is completely broken right now.

````
import { Client } from 'live-mutex';
import * as delay from 'delay';

const mc1 = new Client({
    port: 9394,
    host: '127.0.0.1'
});

mc1.ensure().then(b => {
    b.lockp('a', {ttl: 800000}).then(async res => {
        console.log(`mc1 locked`);
        await delay(10000);
        b.unlockp('a').then(_ => {
            console.log('mc1 unlocked');
            process.exit(0);
        })
    })
})
````

When I try to run it in different console, when process A unlock, process B and C both get the lock at the same time! And sometimes A unlock while B is waiting, B will get the lock but C can get the lock again.

**Comment by hkjeffchan** [comment] 2018-05-28 21:28
live-mutex@0.0.10033 seems to be working fine

**Comment by hkjeffchan** [comment] 2018-05-28 21:35
can confirm: 
live-mutex@0.0.10035 is the last version to be working correctly
newer version will cause two processes to acquire the lock at the same time!

**Comment by ORESoftware** [comment] 2018-05-28 23:11
hmmm thanks, let me take a look

**Comment by ORESoftware** [comment] 2018-05-28 23:43
@hkjeffchan  I see the problem you describe on versions `live-mutex@0.0.10035` through `live-mutex@0.0.10041`.

I am going to try to fix it. In the meantime I would not use this lib for anything critical :)

**Comment by ORESoftware** [comment] 2018-05-29 01:46
I found the problem - it gets a little technical - when a process dies (process.exit(0)), live-mutex has to be careful to make sure that the process that dies was not holding any locks. if the dead process was holding locks we have to release those locks.

in your situation with A, B, and C. A unlocked the lock and then the process died. When A unlocked the lock, it gave the lock to B. But when A died, a routine in the broker unlocked the lock and gave it to C.

I fixed the routine to ensure that if a process died, the lock will only be unlocked if the lock was held by the process that died, there was a bug that unlocked the lock even if the process that died wasn't holding the lock.

**Comment by ORESoftware** [comment] 2018-05-29 08:08
I published another new version - it turns out supporting the command line and programmatic usage is tricky - because at the command line the process can die, but you still want it to keep the lock. I only started supporting command line usage 2 weeks ago or so.

**Comment by hkjeffchan** [comment] 2018-05-29 10:12
Seems like the lock is never timeout now.
tried different value with lockRequestTimeout

**Comment by hkjeffchan** [comment] 2018-05-30 08:49
Works great for my multi key race right now!

**Comment by hkjeffchan** [comment] 2018-05-30 08:52
client option ttl does not support Infinity right now, null is ok.

By the way, this client ttl option is the default for the lockp, right? If client ttl is infinity, the lockp does not need to pass ttl value, right?

UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]:  => "ttl" option needs to be an integer (representing milliseconds).

**Comment by hkjeffchan** [comment] 2018-05-30 11:22
There is something wrong with the process detection but I can't reproduce simply now.

I ran the broker with "node node_modules/live-mutex/dist/lm-start-server 9394" and does not reset it for 2 hours.

5 different node process to test for race conditions and it works initially. But with some force quit and code changing, it starts to behave incorrectly. I start to get the following errors:
Error: Live-Mutex warning => no lock with key -> "a"

And most importantly, more than 1 process can acquire the same key lock at the same time!

I will try to see if it works correctly after restarting the broker process and without killing the client processes.

**Comment by hkjeffchan** [comment] 2018-05-30 11:35
If I pass ttl with Infinity to lockp, it will break. More than 1 process can acquire the lock. It seems it release the lock itself.

**Comment by hkjeffchan** [comment] 2018-05-30 11:37
pass "null" or "infinity" cause the problem, it is working fine if i use 800000 as ttl

it starts to report the following error with null/infinity, so it seems the lock dies and releases itself automatically.

Error: You need to pass the correct uuid, or use force.

**Comment by ORESoftware** [comment] 2018-05-30 21:08
Ok let me fix it lol, thanks for your patience

**Comment by ORESoftware** [comment] 2018-05-31 02:06
The fixes should be implemented in this new version:

`+ live-mutex@0.0.10044`

**Comment by hkjeffchan** [comment] 2018-05-31 08:00
:)
Passing Infinity to lockp cannot acquire the lock at all, passing 800000 will run correctly

**Comment by ORESoftware** [comment] 2018-05-31 08:12
Ok keep passing 800000 then :) I will see what the problem is

**Comment by ORESoftware** [comment] 2018-06-02 02:17
@hkjeffchan I am going close this issue and create a new issue for `Infinity` failing to work.

Btw, if you're willing to share your project codebase I can tell you if the code looks good / if you are using this library optimally etc.

**Closed by ORESoftware** 2018-06-02 02:17 UTC
